---
- name: Converge
  hosts: all

  pre_tasks:
    - name: "Update apt cache"
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family | lower == 'debian'

  tasks:
    - name: "Include ansible-role-dotnet-core"
      include_role:
        name: "ansible-role-dotnet-core"
      vars:
        dotnetcore_version: "3.1"
