---
- name: Verify
  hosts: all

  vars:
    dotnetcore_version: "3.1"

  tasks:
    - name: "Verify .Net Core version: {{ dotnetcore_version }} is installed"
      shell: >-
        dotnet --list-sdks | sed -E 's/([0-9\.]+).*/\1/' | cut -d . -f1,2
      register: dotnet_command

    - assert:
        that: "dotnet_command.rc == 0"
        fail_msg: ".Net Core is not installed"
        success_msg: ".Net Core is installed"

    - assert:
        that: "'{{ dotnetcore_version }}' in dotnet_command.stdout"
        fail_msg: ".Net Core version: {{ dotnetcore_version }} is not installed"
        success_msg: ".Net Core version: {{ dotnetcore_version }} is installed"
